# Generated by Django 4.2.1 on 2023-06-04 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "district_name",
                    models.CharField(default="", max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "division_name",
                    models.CharField(default="", max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "region_name",
                    models.CharField(default="", max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Zimmedar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=200, null=True)),
                ("zehliHalqa", models.CharField(default="", max_length=200, null=True)),
                ("alaqa", models.CharField(default="", max_length=200, null=True)),
                (
                    "district",
                    models.ForeignKey(
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.district",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_name", models.CharField(default="", max_length=100, null=True)),
                (
                    "region_namef",
                    models.ForeignKey(
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.region",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zimmedar_name",
                    models.CharField(default="", max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "zimmedari",
                    models.CharField(
                        choices=[
                            ("Alaqa Zimmedar Naik Aamal", "Alaqa Zimmedar Naik Aamal"),
                            (
                                "District Zimmedar Naik Aamal",
                                "District Zimmedar Naik Aamal",
                            ),
                            (
                                "Division Zimmedar Naik Aamal",
                                "Division Zimmedar Naik Aamal",
                            ),
                            ("State Zimmedar Naik Aamal", "State Zimmedar Naik Aamal"),
                            (
                                "Region Zimmedar Naik Aamal",
                                "Region Zimmedar Naik Aamal",
                            ),
                            ("Hind Zimmedar Naik Aamal", "Hind Zimmedar Naik Aamal"),
                            ("Other Zimmedar", "Other Zimmedar"),
                        ],
                        default="madinah",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("alaqa", models.CharField(default="", max_length=100, null=True)),
                ("taqseem", models.BigIntegerField(default=0, null=True)),
                ("wusool", models.BigIntegerField(default=0, null=True)),
                (
                    "islaheaamal_ijtima_maqam",
                    models.BigIntegerField(default=0, null=True),
                ),
                (
                    "islaheaamal_ijtima_shuraqa",
                    models.BigIntegerField(default=0, null=True),
                ),
                ("tahajjud_ijtima_maqam", models.BigIntegerField(default=0, null=True)),
                (
                    "tahajjud_ijtima_shuraqa",
                    models.BigIntegerField(default=0, null=True),
                ),
                ("sehri_ijtima_maqam", models.BigIntegerField(default=0, null=True)),
                ("sehri_ijtima_shuraqa", models.BigIntegerField(default=0, null=True)),
                ("mehboob_e_attar", models.BigIntegerField(default=0, null=True)),
                (
                    "yaumequfle_madinah_maqam",
                    models.BigIntegerField(default=0, null=True),
                ),
                (
                    "yaumequfle_madinah_shuraqa",
                    models.BigIntegerField(default=0, null=True),
                ),
                (
                    "haftawar_ijtima_main_raat_guzarne_wale_Shuraqa",
                    models.BigIntegerField(default=0, null=True),
                ),
                (
                    "haftawar_ijtima_main_raat_guzarne_wale_maqam",
                    models.BigIntegerField(default=0, null=True),
                ),
                (
                    "district",
                    models.ForeignKey(
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.district",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.division",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.region",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.state",
                    ),
                ),
                (
                    "zimmedar",
                    models.ForeignKey(
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="division",
            name="state_namef",
            field=models.ForeignKey(
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.state",
            ),
        ),
        migrations.AddField(
            model_name="district",
            name="division_namef",
            field=models.ForeignKey(
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.division",
            ),
        ),
    ]
