# Generated by Django 4.2.1 on 2023-06-04 10:08

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Zimmedaris",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zimmedari_name",
                    models.CharField(
                        choices=[
                            ("Alaqa Zimmedar Naik Aamal", "Alaqa Zimmedar Naik Aamal"),
                            (
                                "District Zimmedar Naik Aamal",
                                "District Zimmedar Naik Aamal",
                            ),
                            (
                                "Division Zimmedar Naik Aamal",
                                "Division Zimmedar Naik Aamal",
                            ),
                            ("State Zimmedar Naik Aamal", "State Zimmedar Naik Aamal"),
                            (
                                "Region Zimmedar Naik Aamal",
                                "Region Zimmedar Naik Aamal",
                            ),
                            ("Hind Zimmedar Naik Aamal", "Hind Zimmedar Naik Aamal"),
                            ("Other Zimmedar", "Other Zimmedar"),
                        ],
                        default="",
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="zimmedar",
            name="name",
            field=models.CharField(
                default="",
                max_length=200,
                null=True,
                verbose_name=django.contrib.auth.models.User,
            ),
        ),
    ]
