# Generated by Django 4.2.1 on 2023-06-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_zimmedaris_alter_zimmedar_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="zimmedar",
            name="zimmedari",
            field=models.CharField(
                choices=[
                    ("Alaqa Zimmedar Naik Aamal", "Alaqa Zimmedar Naik Aamal"),
                    ("District Zimmedar Naik Aamal", "District Zimmedar Naik Aamal"),
                    ("Division Zimmedar Naik Aamal", "Division Zimmedar Naik Aamal"),
                    ("State Zimmedar Naik Aamal", "State Zimmedar Naik Aamal"),
                    ("Region Zimmedar Naik Aamal", "Region Zimmedar Naik Aamal"),
                    ("Hind Zimmedar Naik Aamal", "Hind Zimmedar Naik Aamal"),
                    ("Other Zimmedar", "Other Zimmedar"),
                ],
                default="",
                max_length=100,
                null=True,
            ),
        ),
    ]
