# Generated by Django 4.2.1 on 2023-06-04 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_report_zehlihalqa"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hind",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hind_name", models.CharField(default="", max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="region",
            name="hind_namef",
            field=models.ForeignKey(
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.hind",
            ),
        ),
    ]
