# Generated by Django 4.2.1 on 2023-06-04 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_hind_region_hind_namef"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="hind",
            field=models.ForeignKey(
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.hind",
            ),
        ),
    ]
